import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
const canvas=document.querySelector('#canvas'),status=document.querySelector('#status'),detail=document.querySelector('#detail');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;
const scene=new THREE.Scene();scene.background=new THREE.Color('#dce5e3');const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;scene.environmentIntensity=.55;
const camera=new THREE.PerspectiveCamera(55,1,.05,160);const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.minDistance=.6;controls.maxDistance=65;
scene.add(new THREE.HemisphereLight(0xf4f1dc,0x686d59,2));const sun=new THREE.DirectionalLight(0xffefd1,3.3);sun.position.set(-5,15,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-28;sun.shadow.camera.right=20;sun.shadow.camera.top=25;sun.shadow.camera.bottom=-15;sun.shadow.normalBias=.025;scene.add(sun);
const loader=new GLTFLoader(),layout=new THREE.Group(),kit=new THREE.Group();scene.add(layout,kit);let mode='layout',frames=0,last=performance.now(),fps=0;
function box(parent,name,x,y,z,w,h,d,color){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.8}));mesh.name=name;mesh.position.set(x,y,z);mesh.receiveShadow=true;mesh.castShadow=true;parent.add(mesh);return mesh;}
box(layout,'ground',-9,-.06,6,38,.12,32,0xa4b396);box(layout,'plaza',0,-.01,5,9,.08,10,0xd5cbb3);box(layout,'path',-5.2,.01,5,2.4,.06,3.2,0xd7c9aa);
const rampGeo=new THREE.BufferGeometry();const pos=[-6.4,0,3.4,-12.4,.24,3.4,-12.4,.24,6.6,-6.4,0,3.4,-12.4,.24,6.6,-6.4,0,6.6];rampGeo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));rampGeo.computeVertexNormals();const ramp=new THREE.Mesh(rampGeo,new THREE.MeshStandardMaterial({color:0xd7c9aa,side:THREE.DoubleSide,roughness:.8}));ramp.receiveShadow=true;layout.add(ramp);
const fountain=new THREE.Mesh(new THREE.CylinderGeometry(1.8,1.8,.9,48),new THREE.MeshStandardMaterial({color:0x819e9b}));fountain.position.set(0,.45,4);layout.add(fountain);
const marker=new THREE.Mesh(new THREE.CylinderGeometry(.2,.2,1.6,16),new THREE.MeshStandardMaterial({color:0x197b77}));marker.position.set(-12.4,1.04,5);layout.add(marker);
const old=(await loader.loadAsync('./layout-prototype.glb')).scene;old.position.set(-17,0,5);old.rotation.y=-Math.PI/2;old.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});layout.add(old);
const cameras={A:[[-4,1.65,7.8],[-13.3,1.8,5]],B:[[-8,1.65,6.8],[-13.3,1.8,5]],C:[[-6.4,3.25,5],[-13.5,2.1,5]],D:[[-7,28,10],[-10,0,6]]};
let kitReady=false;async function loadKit(){if(kitReady)return;const data=await loader.loadAsync('./exports/campus-kit-assembly.glb');kit.add(data.scene);data.scene.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});box(kit,'review-ground',0,-.09,0,30,.12,22,0xc9c9b9);kitReady=true;}
function fixed(id){const [p,t]=cameras[id];camera.position.fromArray(p);controls.target.fromArray(t);controls.update();}
function setMode(next){mode=next;layout.visible=mode==='layout';kit.visible=mode==='kit';document.querySelector('#layout').setAttribute('aria-pressed',String(mode==='layout'));document.querySelector('#kit').setAttribute('aria-pressed',String(mode==='kit'));if(mode==='layout'){fixed(document.querySelector('#camera').value);detail.textContent='Existing model and trigger anchor retained. Proposed ramp/path shown; full game props and school-device acceptance remain separate.';}else{camera.position.set(10,8,14);controls.target.set(0,1,1.6);controls.update();detail.textContent='Textured component assembly and individual modules. Appearance is a review candidate; the complete Studio is the next stage.';} }
document.querySelector('#layout').onclick=()=>setMode('layout');document.querySelector('#kit').onclick=async()=>{try{await loadKit();setMode('kit');}catch(error){status.textContent='Kit export is not yet available: '+error.message;}};document.querySelector('#camera').onchange=()=>{setMode('layout');};document.querySelector('#orbit').onclick=()=>{if(mode==='kit'){camera.position.set(10,8,14);controls.target.set(0,1,1.6);}else fixed('D');};
const errors=[];window.addEventListener('error',e=>errors.push(e.message));
window.kitReview={setMode,loadKit,fixed,scene,renderer,camera,layout,kit,errors,get stats(){return {mode,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,textures:renderer.info.memory.textures,fps:Math.round(fps)}},checkLayout(){const samples=Array.from({length:85},(_,i)=>({x:-4-i*.1,z:5}));return {samples:samples.length,clearOfFountain:samples.every(p=>Math.hypot(p.x,p.z-4)>2),clearOfStudioBlock:samples.every(p=>p.x> -13.2),landingInTrigger:-12.4> -13.6&&-12.4< -10.8,pathWidth:3.2,rampRise:.24,rampRun:6,limits:'Isolated test geometry; full runtime props/collision and school device are not certified.'};}};
function resize(){const rect=canvas.getBoundingClientRect();renderer.setSize(rect.width,rect.height,false);camera.aspect=rect.width/rect.height;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(canvas);resize();await loadKit();setMode('kit');window.workbenchReady=true;
renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);frames++;const now=performance.now();if(now-last>1000){fps=frames*1000/(now-last);frames=0;last=now;status.textContent=(mode==='layout'?'Layout review':'Textured kit review')+' · '+renderer.info.render.calls+' draw calls · '+renderer.info.render.triangles.toLocaleString()+' triangles · local preview '+Math.round(fps)+' fps';}});
